// NOTE: THIS REQUIRES A CLEAN DATABASE (at least for the created test user Codey and email Test@mail.com)

describe('Registers successfully', () => {
  it('should navigate to welcome page successfully', () => {
    cy.visit('localhost:3000/')
    cy.url().should('include', 'localhost:3000')
  })

  it('should navigate to register page successfully', () => {
    cy.visit('localhost:3000/')
    cy.get('button[name="login-register-button"]')
      .click()
    cy.url().should('include', 'localhost:3000/login')
  })

  it('should register successfully after filling in form', () => {
    cy.visit('localhost:3000/')
    cy.get('button[name="login-register-button"]')
      .click()
    cy.get('button[name="switch-to-register"]')
      .click()
    cy.get('input[name="name"]')
      .focus()
      .type('Codey')
    cy.get('input[name="email"]')
      .focus()
      .type('test@mail.com')
    cy.get('input[name="password"]')
      .focus()
      .type('123')
    cy.get('input[name="confirm"]')
      .focus()
      .type('123')
    cy.get('button[name="register-button"]')
      .click()
    cy.url().should('include', 'localhost:3000/')
  })
})

describe('Creates a new game successfully', () => {
  beforeEach(() => {
    cy.visit('localhost:3000/')
    cy.get('button[name="login-register-button"]')
      .click()
    cy.get('input[name="email"]')
      .focus()
      .type('test@mail.com')
    cy.get('input[name="password"]')
      .focus()
      .type('123')
    cy.get('button[name="login-button"]')
      .click()
  })

  it('Create new game with name test game', () => {
    cy.get('input[name="new-game-input"]')
      .focus()
      .type('test game')
    cy.get('button[name="create-game"]')
      .click()
  })
})

describe('Start game and end it, loading results page', () => {
  beforeEach(() => {
    cy.visit('localhost:3000/')
    cy.get('button[name="login-register-button"]')
      .click()
    cy.get('input[name="email"]')
      .focus()
      .type('test@mail.com')
    cy.get('input[name="password"]')
      .focus()
      .type('123')
    cy.get('button[name="login-button"]')
      .click()
  })

  it('Start game button', () => {
    cy.get('button[name="start-quiz"]')
      .click()
  })
  it('end game button and view results', () => {
    cy.get('button[name="view-results"]')
      .click()
    cy.get('button[name="stop-game"]')
      .click()
    cy.url().should('include', 'localhost:3000/game/result')
  })
})

describe('Loggin out and log back in', () => {
  before(() => {
    cy.visit('localhost:3000/')
    cy.get('button[name="login-register-button"]')
      .click()
    cy.url().should('include', 'localhost:3000/login')
    cy.get('input[name="email"]')
      .focus()
      .type('test@mail.com')
    cy.get('input[name="password"]')
      .focus()
      .type('123')
    cy.get('button[name="login-button"]')
      .click()
  })
  after(() => {
    cy.visit('localhost:3000/')
    cy.get('button[name="login-register-button"]')
      .click()
    cy.url().should('include', 'localhost:3000/login')
    cy.get('input[name="email"]')
      .focus()
      .type('test@mail.com')
    cy.get('input[name="password"]')
      .focus()
      .type('123')
    cy.get('button[name="login-button"]')
      .click()
  })
  it('Log out', () => {
    cy.get('button[name="logout"]')
      .click()
  })
})
